# Mini Project1
### 20181531 김연주

In [2]:
import pandas as pd
import numpy as np

emnist = pd.read_csv("csv/emnist-digits-train.csv")
emnist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239999 entries, 0 to 239998
Columns: 785 entries, 8 to 0.520
dtypes: int64(785)
memory usage: 1.4 GB


In [3]:
emnist.head()

8  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.511  0.512  0.513  \
0  9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.514  0.515  0.516  0.517  0.518  0.519  0.520  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [4]:
emnist.shape

(239999, 785)

In [5]:
X = emnist.drop(["8"], axis=1)
X

0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...  0.511  0.512  \
0       0    0    0    0    0    0    0    0    0    0  ...      0      0   
1       0    0    0    0    0    0    0    0    0    0  ...      0      0   
2       0    0    0    0    0    0    0    0    0    0  ...      0      0   
3       0    0    0    0    0    0    0    0    0    0  ...      0      0   
4       0    0    0    0    0    0    0    0    0    0  ...      0      0   
...    ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
239994  0    0    0    0    0    0    0    0    0    0  ...      0      0   
239995  0    0    0    0    0    0    0    0    0    0  ...      0      0   
239996  0    0    0    0    0    0    0    0    0    0  ...      0      0   
239997  0    0    0    0    0    0    0    0    0    0  ...      0      0   
239998  0    0    0    0    0    0    0    0    0    0  ...      0      0   

        0.513  0.514  0.515  0.516  0.517  0.518  0.519  0.520  
0           0      0      0      0      0      0      0      0  
1           0      0      0      0      0      0      0      0  
2           0      0      0      0      0      0      0      0  
3           0      0      0      0      0      0      0      0  
4           0      0      0      0      0      0      0      0  
...       ...    ...    ...    ...    ...    ...    ...    ...  
239994      0      0      0      0      0      0      0      0  
239995      0      0      0      0      0      0      0      0  
239996      0      0      0      0      0      0      0      0  
239997      0      0      0      0      0      0      0      0  
239998      0      0      0      0      0      0      0      0  

[239999 rows x 784 columns]

In [6]:
y=emnist["8"]
y

0         9
1         6
2         3
3         6
4         6
         ..
239994    4
239995    2
239996    1
239997    1
239998    0
Name: 8, Length: 239999, dtype: int64

## RandomForest

In [7]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)

In [8]:
model.fit(X,y)

RandomForestClassifier(random_state=42)

In [9]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X, y, cv=10, scoring="accuracy")
scores

array([0.98133333, 0.98033333, 0.98145833, 0.98083333, 0.98025   ,
       0.982     , 0.982     , 0.98104167, 0.98016667, 0.98112421])

In [10]:
scores.mean() 

0.9810540880175562

In [11]:
from sklearn.ensemble import ExtraTreesClassifier

extra_trees_clf = ExtraTreesClassifier(n_estimators=50, random_state=42)
extra_trees_clf.fit(X, y)

ExtraTreesClassifier(n_estimators=50, random_state=42)

In [12]:
from sklearn.model_selection import cross_val_score

extra_fold_score = cross_val_score(extra_trees_clf, X, y, cv=10, scoring="accuracy")
extra_fold_score

array([0.98170833, 0.980625  , 0.98279167, 0.981875  , 0.980875  ,
       0.9835    , 0.98245833, 0.982125  , 0.98083333, 0.9816659 ])

In [13]:
def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard deviation", scores.std())
    
display_scores(extra_fold_score)

Scores: [0.98170833 0.980625   0.98279167 0.981875   0.980875   0.9835
 0.98245833 0.982125   0.98083333 0.9816659 ]
Mean: 0.9818457569412615
Standard deviation 0.0008714469504557418


In [14]:
from sklearn.ensemble import ExtraTreesClassifier

model2 = ExtraTreesClassifier(random_state=42)

In [15]:
model2.fit(X,y)

ExtraTreesClassifier()

In [16]:
from sklearn.model_selection import cross_val_score

scores2 = cross_val_score(model2, X, y,
                        scoring="accuracy", cv=10)

In [17]:
scores2

array([0.98358333, 0.98245833, 0.982875  , 0.98316667, 0.98254167,
       0.983375  , 0.98320833, 0.983375  , 0.98208333, 0.98279095])

In [18]:
display_scores(scores2)

Scores: [0.98358333 0.98245833 0.982875   0.98316667 0.98254167 0.983375
 0.98320833 0.983375   0.98208333 0.98279095]
Mean: 0.9829457616289569
Standard deviation 0.00045457313873176154


In [19]:
from sklearn.svm import SVC
svm_clf = SVC(kernel="linear", probability=True, random_state=42)

In [ ]:
svm_clf.fit(X,y)

In [ ]:
svm_clf_score = cross_val_score(svm_clf, X, y, cv=10, scoring="accuracy")
display_scores(svm_clf_score)

## => 결과: 0.9830749302054252